name: "Code quality checks"

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Run lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Run build
        run: pnpm typecheck

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: pnpm test

  dry_publish:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    permissions:
      contents: none
      id-token: none

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish --dry-run
